---
all:
  hosts:
    k8s-master-01:
      ansible_host: k8s-master-01
    k8s-master-02:
      ansible_host: k8s-master-02
    k8s-master-03:
      ansible_host: k8s-master-03
    k8s-worker-01:
      ansible_host: k8s-worker-01
    k8s-worker-02:
      ansible_host: k8s-worker-02
    k8s-worker-03:
      ansible_host: k8s-worker-03
  children:
    kube_control_plane:
      hosts:
        k8s-master-01:
        k8s-master-02:
        k8s-master-03:
    kube_node:
      hosts:
        k8s-worker-01:
        k8s-worker-02:
        k8s-worker-03:
    etcd:
      hosts:
        k8s-master-01:
        k8s-master-02:
        k8s-master-03:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/vgorshkov/.ssh/netology-ext-key
    ansible_ssh_common_args: '-F /home/vgorshkov/.ssh/config'
