all:
  hosts:
    k8s-master-ru-central1-a:
    k8s-master-ru-central1-b:
    k8s-master-ru-central1-d:
    k8s-worker-ru-central1-a:
    k8s-worker-ru-central1-b:
    k8s-worker-ru-central1-d:
  children:
    kube_control_plane:
      hosts:
        k8s-master-ru-central1-a:
        k8s-master-ru-central1-b:
        k8s-master-ru-central1-d:
    kube_node:
      hosts:
        k8s-worker-ru-central1-a:
        k8s-worker-ru-central1-b:
        k8s-worker-ru-central1-d:
    etcd:
      hosts:
        k8s-master-ru-central1-a:
        k8s-master-ru-central1-b:
        k8s-master-ru-central1-d:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/vgorshkov/.ssh/netology-ext-key
    ansible_ssh_common_args: '-F /home/vgorshkov/.ssh/config'
