[nat]
yc-nat-instance

[nat:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/vgorshkov/.ssh/netology-ext-key
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-F /home/vgorshkov/.ssh/config'
