apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: infra
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: infra
  endpoints:
    - port: metrics
      scheme: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
