apiVersion: v1
kind: Service
metadata:
  name: infra
  namespace: default
  labels:
    app: infra
spec:
  type: ClusterIP
  selector:
    app: infra
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
