---
prometheus:
  prometheusSpec:
    retention: 24h
    retentionSize: 1GB

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi

    # Временное хранилище EmptyDir.
    storageSpec: {}

alertmanager:
  alertmanagerSpec:
    retention: 24h

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi

    # Временное хранилище EmptyDir.
    storage: {}

grafana:
  grafana.ini:
    server:
      root_url: "http://51.250.75.1/grafana/"
      serve_from_sub_path: true

  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

  sidecar:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  # Временное хранилище EmptyDir.
  persistence:
    enabled: false
