apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-deployer
  namespace: default
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    resourceNames:
      - infra
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-deployer
  namespace: default
subjects:
  - kind: ServiceAccount
    name: infra-deployer
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infra-deployer
